'use client';
import {useState,useEffect} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {approveProspectsAction,updateProspectStatusAction,updateCampaignStatusAction,markOutreachResponseAction,syncOutreachAction,type OutreachActionState} from '@/actions/outreach-actions';
import {personalize} from '@/lib/outreach-policy';
type Prospect={id:string;name:string;email:string;company:string|null;status:string;permissionGranted:boolean;replySubject:string|null;sentAt:string|null;repliedAt:string|null;due:number|null;attempts:{step:number;status:string;sentAt:string|null}[];customSubject:string|null;customBody:string|null};
type Campaign={id:string;name:string;status:string;subject:string;body:string;followup1Body:string|null;followup2Body:string|null;purpose:string;dailyLimit:number};
export function CampaignDetailClient({campaign,initialProspects}:{campaign:Campaign;initialProspects:Prospect[]}){
 const router=useRouter();const [pending,setPending]=useState(false);const [selected,setSelected]=useState<string[]>([]);const [note,setNote]=useState('');const [confirmed,setConfirmed]=useState(false);const [feedback,setFeedback]=useState('');const [filter,setFilter]=useState('ALL');const [previewId,setPreviewId]=useState(initialProspects[0]?.id||'');
 useEffect(()=>{const timer=setInterval(()=>router.refresh(),30000);return()=>clearInterval(timer)},[router]);
 const act=async(fn:()=>Promise<OutreachActionState>)=>{if(pending)return;setPending(true);try{const result=await fn();setFeedback(result.message||(result.success?'Saved.':'Could not save.'));if(result.success)router.refresh();}catch{setFeedback('Action failed. Refresh and try again.');}finally{setPending(false);}};
 const eligible=initialProspects.filter(p=>['PENDING','SELECTED'].includes(p.status));
 const visible=initialProspects.filter(p=>filter==='ALL'||filter==='REPLIED'&&p.repliedAt||filter==='FOLLOWUP1'&&p.due===1||filter==='FOLLOWUP2'&&p.due===2||filter==='REVIEW'&&p.attempts.some(a=>['UNKNOWN','CLAIMED'].includes(a.status)));
 const preview=initialProspects.find(p=>p.id===previewId);
 return <div className="space-y-6 text-[#122C57]">
  <Link href="/admin/outreach" className="text-sm underline">← Campaigns</Link><h1 className="font-serif text-3xl">{campaign.name}</h1>
  <p>{campaign.status} · {campaign.purpose==='TEST'?'Trusted-recipient delivery test':'Prospect campaign'} · Campaign cap {campaign.dailyLimit}/day</p>
  <p role="status" className="text-sm">{feedback}</p>
  <div className="bg-white border p-5 space-y-4"><h2 className="font-semibold">Activate the reviewed sequence</h2><p className="text-sm">Select recipients, record why they may receive these emails, preview the content, then activate. Scheduling continues on the server when you close this page.</p>
   <label className="block text-sm">Permission / source note<textarea value={note} onChange={e=>setNote(e.target.value)} className="block w-full border p-2 mt-1" placeholder="For example: requested this information during our call on…" maxLength={1000}/></label>
   <label className="flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>These selected recipients requested or agreed to receive these emails. Delivery-test recipients are trusted people expecting the test.</label>
   <div className="flex flex-wrap gap-3"><button disabled={pending||!selected.length||!confirmed} className="border px-4 py-2 disabled:opacity-40" onClick={()=>act(async()=>{const a=await approveProspectsAction(selected,note);if(!a.success)return a;return updateProspectStatusAction(selected,'SELECTED');})}>Approve {selected.length} selected</button><button disabled={pending} className="bg-[#122C57] text-white px-4 py-2 disabled:opacity-40" onClick={()=>act(()=>updateCampaignStatusAction(campaign.id,'ACTIVE'))}>Activate</button><button disabled={pending} className="border px-4 py-2" onClick={()=>act(()=>updateCampaignStatusAction(campaign.id,'PAUSED'))}>Pause</button><button disabled={pending} className="border px-4 py-2" onClick={()=>act(syncOutreachAction)}>Check inbox</button></div>
   <p className="text-xs text-slate-500">The scheduler and Hostinger credentials must be configured before sending. Pausing cannot recall an email already in flight. Imported data is not proof of permission.</p>
  </div>
  <details className="bg-white border p-5"><summary className="cursor-pointer font-semibold">Preview first message and follow-ups</summary><label className="block mt-3">Recipient<select className="block border p-2" value={previewId} onChange={e=>setPreviewId(e.target.value)}>{initialProspects.map(p=><option key={p.id} value={p.id}>{p.email}</option>)}</select></label>{preview&&<div className="space-y-3 mt-3"><h3>{personalize(preview.customSubject||campaign.subject,preview)}</h3>{[preview.customBody||campaign.body,campaign.followup1Body,campaign.followup2Body].map((body,i)=><div key={i}><strong>{['First message','First follow-up · after 4 business days','Second follow-up · after another 5 business days'][i]}</strong><pre className="whitespace-pre-wrap font-sans text-sm p-3 bg-slate-50">{body?personalize(body,preview):'Not configured'}</pre></div>)}<p className="text-xs">Your configured mailing address and unsubscribe link are appended during sending.</p></div>}</details>
  <div className="flex gap-3 items-center"><label>View <select className="border p-2" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All recipients</option><option value="FOLLOWUP1">First follow-up due</option><option value="FOLLOWUP2">Second follow-up due</option><option value="REPLIED">Replies</option><option value="REVIEW">Uncertain dispatches</option></select></label><button className="underline text-sm" onClick={()=>setSelected(eligible.map(p=>p.id))}>Select pending</button><button className="underline text-sm" onClick={()=>setSelected([])}>Clear selection</button></div>
  <div className="overflow-x-auto border bg-white"><table className="w-full text-sm"><thead><tr>{['Select','Recipient','Status','Permission','Sequence / reply','Actions'].map(x=><th key={x} className="text-left p-3">{x}</th>)}</tr></thead><tbody>{visible.map(p=><tr key={p.id} className="border-t"><td className="p-3">{['PENDING','SELECTED'].includes(p.status)&&<input aria-label={`Select ${p.email}`} type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,p.id]:s.filter(id=>id!==p.id))}/>}</td><td className="p-3">{p.name}<span className="block text-xs">{p.email}</span><span className="block text-xs">{p.company}</span></td><td className="p-3">{p.status}</td><td className="p-3">{p.permissionGranted?'Recorded':'Needed'}</td><td className="p-3">{p.attempts.map(a=><p key={a.step}>Step {a.step}: {a.status}</p>)}{p.replySubject&&<p>{p.replySubject}</p>}{p.due!==null&&<p>Step {p.due} due</p>}</td><td className="p-3"><div className="flex flex-wrap gap-2">{(['REPLIED','UNSUBSCRIBED','BOUNCED'] as const).map(status=><button key={status} disabled={pending} className="text-xs underline" onClick={()=>act(()=>markOutreachResponseAction(p.id,status))}>Mark {status.toLowerCase()}</button>)}</div></td></tr>)}</tbody></table></div>
 </div>;
}
