ALTER TABLE "AiCallback"
ADD COLUMN IF NOT EXISTS "transcriptTurns" JSONB,
ADD COLUMN IF NOT EXISTS "analysisStatus" TEXT NOT NULL DEFAULT 'NOT_REQUESTED',
ADD COLUMN IF NOT EXISTS "analysis" JSONB,
ADD COLUMN IF NOT EXISTS "analysisStartedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "recapStatus" TEXT NOT NULL DEFAULT 'NOT_REQUESTED',
ADD COLUMN IF NOT EXISTS "recapSubject" TEXT,
ADD COLUMN IF NOT EXISTS "recapBody" TEXT,
ADD COLUMN IF NOT EXISTS "recapError" TEXT,
ADD COLUMN IF NOT EXISTS "recapSentAt" TIMESTAMP(3);