import {redirect} from 'next/navigation';
import Link from 'next/link';
import {PhoneCall,CheckCircle2,Clock3,Mail,AlertTriangle,ArrowUpRight,Globe2,MessageSquareText} from 'lucide-react';
import {prisma} from '@/lib/prisma';
import {getAdminSession} from '@/lib/auth';
import {callbackRoute} from '@/lib/ai-callback-policy';
import {AnalysisSchema} from '@/lib/callback-recap-analysis';
import {callbackConfiguration} from '@/lib/ai-callbacks';
import {RefreshCallbacks} from './refresh';
import {AnalysisConnectionCheck} from './connection-check';
export const dynamic='force-dynamic';
export const maxDuration=120;
const stamp=(date:Date|null)=>date?date.toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'}):'Pending';
const label=(s:string)=>s.replaceAll('_',' ').toLowerCase().replace(/^./,c=>c.toUpperCase());
function Badge({value}:{value:string}){const color=['CONNECTED','CHECKED','SENT'].includes(value)?'bg-emerald-50 text-emerald-800 border-emerald-200':['REVIEW','UNKNOWN','REJECTED','FAILED','BLOCKED','EXPIRED'].includes(value)?'bg-amber-50 text-amber-900 border-amber-200':'bg-slate-50 text-slate-600 border-slate-200';return <span className={'inline-flex rounded-full border px-3 py-1 text-xs font-semibold '+color}>{value==='SENT'?'Email accepted':label(value)}</span>;}
export default async function CallbacksPage({searchParams:p}:{searchParams:{source?:string;status?:string;page?:string;q?:string;recap?:string}}){
 const session=await getAdminSession();if(!session)redirect('/admin/login');if(session.role!=='ADMIN')redirect('/admin');
 const config=callbackConfiguration();
 const source=['BOOKING','CONTACT'].includes(p.source||'')?p.source:undefined;
 const statuses=['QUEUED','BLOCKED','SKIPPED','DISPATCHING','ACCEPTED','CONNECTED','NO_ANSWER','BUSY','FAILED','REJECTED','UNKNOWN','EXPIRED'];
 const status=statuses.includes(p.status||'')?p.status:undefined;
 const recapStates=['PENDING','SENDING','SENT','REVIEW','SUPPRESSED','BLOCKED','UNKNOWN','REJECTED','NOT_REQUESTED','NOT_APPLICABLE'];
 const recap=recapStates.includes(p.recap||'')?p.recap:undefined;
 const q=(p.q||'').trim().slice(0,100),page=Math.max(1,Math.min(10000,parseInt(p.page||'1',10)||1));
 const where={...(source?{source}:{}),...(status?{status}:{}),...(recap?{recapStatus:recap}:{}),...(q?{lead:{OR:[{name:{contains:q,mode:'insensitive' as const}},{email:{contains:q,mode:'insensitive' as const}},{phone:{contains:q}}]}}:{})};
 const [calls,total,groups,emailGroups]=await Promise.all([prisma.aiCallback.findMany({where,include:{lead:true},orderBy:{createdAt:'desc'},skip:(page-1)*20,take:20}),prisma.aiCallback.count({where}),prisma.aiCallback.groupBy({by:['status'],_count:{_all:true}}),prisma.aiCallback.groupBy({by:['recapStatus'],_count:{_all:true}})]);
 const count=(values:string[])=>groups.filter(g=>values.includes(g.status)).reduce((sum,g)=>sum+g._count._all,0);
 const emailCount=(values:string[])=>emailGroups.filter(g=>values.includes(g.recapStatus)).reduce((sum,g)=>sum+g._count._all,0);
 const href=(n:number)=>'/admin/callbacks?'+new URLSearchParams({...(source?{source}:{}),...(status?{status}:{}),...(recap?{recap}:{}),...(q?{q}:{}),page:String(n)});
 return <div className="max-w-7xl space-y-6 pb-12 text-[#122C57]">
  <header className="relative overflow-hidden rounded-2xl bg-[#122C57] p-6 text-white md:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[0.22em] text-[#E5B554]">Gravity · Voice operations</p><h1 className="font-serif text-3xl md:text-4xl">Every conversation. A clear next step.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-200">Follow each enquiry from the first call to the caller’s needs and a checked conversation recap.</p></div><div className="flex items-center gap-2 rounded-full border border-white/20 px-3 py-2 text-xs"><span className={'h-2 w-2 rounded-full '+(config.enabled&&!config.missing.length?'bg-emerald-400':'bg-amber-400')}/>{config.enabled&&!config.missing.length?'Callbacks active':'Setup required'}</div></div><div className="mt-6 flex flex-wrap gap-5 border-t border-white/15 pt-4 text-xs text-slate-200"><span className="flex gap-2"><Globe2 size={15}/>US +1 443 645 5768</span><span>India +91 79714 42620</span><span>All timestamps · IST</span></div></header>
  {config.missing.length>0&&<div role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm">Setup needed: {config.missing.join(', ')}</div>}
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{title:'Conversations',value:count(['CONNECTED']),icon:PhoneCall,note:'Connected calls'},{title:'In progress',value:count(['QUEUED','DISPATCHING','ACCEPTED']),icon:Clock3,note:'Waiting for a call result'},{title:'Recaps accepted',value:emailCount(['SENT']),icon:Mail,note:'Accepted by mail server'},{title:'Recaps to review',value:emailCount(['REVIEW','BLOCKED','UNKNOWN','REJECTED','SENDING']),icon:AlertTriangle,note:'Check delivery or analysis'}].map(({title,value,icon:Icon,note})=><div key={title} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex justify-between gap-2 text-sm text-slate-600"><span>{title}</span><Icon size={18}/></div><p className="my-3 text-3xl font-semibold tabular-nums">{value}</p><p className="text-xs text-slate-500">{note} · all time</p></div>)}</div>
  <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Conversation inbox</h2><p className="mt-1 text-xs text-slate-500">{total} matching records · 20 per page · refreshes every 30 seconds</p></div><RefreshCallbacks/></div><form className="mt-5 grid gap-3 md:grid-cols-5"><label className="text-xs font-medium md:col-span-2">Find a caller<input name="q" defaultValue={q} placeholder="Name, email or phone" className="mt-1 w-full rounded-lg border border-slate-300 p-2.5 text-sm"/></label><label className="text-xs font-medium">Source<select name="source" defaultValue={source||''} className="mt-1 w-full rounded-lg border border-slate-300 p-2.5 text-sm"><option value="">All sources</option><option value="BOOKING">Meeting bookings</option><option value="CONTACT">Contact forms</option></select></label><label className="text-xs font-medium">Call status<select name="status" defaultValue={status||''} className="mt-1 w-full rounded-lg border border-slate-300 p-2.5 text-sm"><option value="">All calls</option>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label className="text-xs font-medium">Recap email<select name="recap" defaultValue={recap||''} className="mt-1 w-full rounded-lg border border-slate-300 p-2.5 text-sm"><option value="">All recaps</option>{recapStates.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><div className="flex gap-3 md:col-span-5"><button className="rounded-lg bg-[#122C57] px-5 py-2 text-sm text-white">Apply filters</button><Link href="/admin/callbacks" className="px-3 py-2 text-sm underline">Reset</Link></div></form></section>
  {!calls.length&&<div className="rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center"><MessageSquareText className="mx-auto mb-3 text-slate-400"/><h2 className="font-semibold">No conversations in this view</h2><p className="mt-2 text-sm text-slate-500">New website enquiries and bookings appear here. Try clearing the filters.</p></div>}
  {calls.map(call=>{const parsed=AnalysisSchema.safeParse(call.analysis),analysis=parsed.success?parsed.data:null,route=callbackRoute(call.phone);return <article key={call.id} className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap justify-between gap-4 border-b border-slate-100 p-5"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{call.lead.name}</h2><span className="rounded bg-slate-100 px-2 py-1 text-xs">{route?.country||'Other region'}</span></div><p className="mt-1 break-all text-sm text-slate-500">{call.phone||'No phone'} · {call.lead.email}</p><p className="mt-2 text-xs text-slate-500">{call.source==='BOOKING'?'Meeting booking':'Website enquiry'} · {stamp(call.createdAt)}</p></div><div className="flex flex-wrap items-start gap-2"><Badge value={call.status}/><Badge value={call.recapStatus}/></div></div>
   <div className="grid gap-6 p-5 lg:grid-cols-3"><section className="lg:col-span-2"><div className="mb-3 flex flex-wrap items-center gap-3"><h3 className="text-sm font-semibold">What the caller wants</h3>{analysis&&<span className="rounded-full bg-[#122C57]/5 px-3 py-1 text-xs">{label(analysis.intent)}</span>}<Badge value={call.analysisStatus}/></div>{analysis?.needs.length?<ul className="space-y-3">{analysis.needs.map((need,i)=><li key={i} className="border-l-2 border-[#D4A64A] pl-3"><p className="text-sm leading-6">{need.text}</p><details className="mt-1 text-xs text-slate-500"><summary className="cursor-pointer">Caller evidence · turn {need.turn+1}</summary><blockquote className="mt-2 leading-5">“{need.evidence}”</blockquote></details></li>)}</ul>:<p className="text-sm text-slate-500">{call.status==='CONNECTED'?'A usable caller transcript and successful analysis are needed before a recap can be sent.':'Intent appears after a connected call returns a transcript.'}</p>}
   {analysis&&analysis.nextSteps.length>0&&<div className="mt-5 rounded-lg bg-slate-50 p-4"><h4 className="mb-2 text-xs font-semibold uppercase tracking-wide">Caller-requested next steps</h4><ul className="space-y-2 text-sm">{analysis.nextSteps.map((step,i)=><li key={i}>{step.text}<details className="mt-1 text-xs text-slate-500"><summary className="cursor-pointer">View evidence</summary>{step.evidence}</details></li>)}</ul></div>}<p className="mt-4 text-xs text-slate-400">AI interpretation checked against transcript evidence. Review against the transcript when accuracy matters.</p></section>
   <aside className="rounded-xl bg-slate-50 p-4"><h3 className="mb-4 text-sm font-semibold">Call → recap</h3><ol className="space-y-4 text-xs">{[['Enquiry saved',stamp(call.createdAt)],['Call requested',stamp(call.requestedAt)],['Call result',call.completedAt?stamp(call.completedAt)+(call.duration!==null?' · '+call.duration+'s':''):'Waiting for Sarvam'],['Recap email',call.recapSentAt?stamp(call.recapSentAt):label(call.recapStatus)]].map(([name,value])=><li key={name} className="flex gap-3"><CheckCircle2 size={15} className="mt-0.5 shrink-0 text-slate-400"/><div><p className="font-medium">{name}</p><p className="mt-1 text-slate-500">{value}</p></div></li>)}</ol><p className="mt-4 border-t pt-3 text-xs text-slate-500">Caller ID: {route?.connection.agent_phone_number||'Not routed'}</p></aside></div>
   {(call.error||call.recapError)&&<div role="status" className="mx-5 mb-5 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{call.error&&<p>{call.error}</p>}{call.recapError&&<p>{call.recapError}</p>}</div>}
   {(call.analysisStatus==='PROCESSING'&&call.analysisStartedAt&&Date.now()-call.analysisStartedAt.getTime()>120000||call.recapStatus==='SENDING')&&<p className="px-5 pb-4 text-xs text-amber-800">Processing or delivery reservation is open. If it remains unchanged, check provider logs before retrying.</p>}
   <div className="grid gap-3 border-t border-slate-100 p-5 md:grid-cols-2"><details className="rounded-lg border p-3 text-sm"><summary className="cursor-pointer font-medium">Recap email preview</summary><p className="mt-3 font-medium">{call.recapSubject||'No recap prepared'}</p><pre className="mt-3 whitespace-pre-wrap break-words font-sans text-sm leading-6 text-slate-600">{call.recapBody||'Emails are held when evidence is missing, analysis needs review, or the caller declines contact.'}</pre></details><details className="rounded-lg border p-3 text-sm"><summary className="cursor-pointer font-medium">Transcript & original agent summary</summary><p className="mt-3 text-xs text-slate-500">Provider summary (not independently verified): {call.summary||'Not supplied'}</p><pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap break-words font-sans text-sm leading-6">{call.transcript||'No transcript received'}</pre><p className="mt-3 break-all text-xs text-slate-400">Lead {call.leadId} · Attempt {call.attemptId||'Pending'}</p></details></div><div className="flex justify-end border-t border-slate-100 px-5 py-3"><Link className="inline-flex items-center gap-1 text-xs font-semibold" href={call.source==='BOOKING'?'/admin/bookings':'/admin/leads'}>Open source records <ArrowUpRight size={14}/></Link></div></article>})}
  <nav aria-label="Conversation pages" className="flex items-center justify-between text-sm"><span>Page {page}</span><div className="flex gap-4">{page>1&&<Link className="underline" href={href(page-1)}>Previous</Link>}{page*20<total&&<Link className="underline" href={href(page+1)}>Next</Link>}</div></nav>
  <details className="rounded-xl border border-slate-200 bg-white p-5 text-sm"><summary className="cursor-pointer font-semibold">Processing settings & connection check</summary><div className="mt-4 space-y-3 text-slate-600"><p>Only new connected calls are analysed. Missing evidence and failed checks need review; missed calls do not receive conversation recaps. No historical calls are emailed automatically.</p><p>Email accepted means SMTP accepted the message, not confirmed inbox delivery. Recaps use the original form email; spoken email addresses never replace it.</p><AnalysisConnectionCheck/></div></details>
 </div>;
}
