const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path'),ts=require('typescript');
function load(file,mocks={},globals={}){const absolute=path.resolve(__dirname,'..',file);const module={exports:{}};const source=ts.transpileModule(fs.readFileSync(absolute,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;vm.runInNewContext(source,{module,exports:module.exports,require:id=>id in mocks?mocks[id]:id.startsWith('.')?load(path.relative(path.join(__dirname,'..'),path.resolve(path.dirname(absolute),id+'.ts')),mocks,globals):require(id),process,Buffer,URL,Request,Response,Date,AbortSignal,console,...globals});return module.exports;}
const policy=load('src/lib/ai-callback-policy.ts');
test('normalizes Indian and international callback numbers and rejects invalid values',()=>{assert.equal(policy.normalizeCallbackPhone('78143 51011'),'+917814351011');assert.equal(policy.normalizeCallbackPhone('+1 (202) 555-0111'),'+12025550111');assert.equal(policy.normalizeCallbackPhone('bad'),null);assert.equal(policy.normalizeCallbackPhone('+000123456789'),null);});
test('per-call token rejects tampering',()=>{const hash=policy.hashCallbackToken('secret');assert.equal(policy.validCallbackToken('secret',hash),true);assert.equal(policy.validCallbackToken('wrong',hash),false);assert.equal(policy.validCallbackToken('secret',null),false);});
test('payload uses provided agent and metadata and does not invent gender',()=>{const payload=policy.callbackPayload({id:'c1',leadId:'l1',phone:'+917814351011',source:'BOOKING'},{name:'Test',businessName:null,serviceInterest:'Audit',message:'Test only'},'token');assert.equal(payload.app_config.app_version,9);assert.equal(payload.app_config.agent_variables.gender,'');assert.equal(payload.webhook_config.metadata.lead_id,'l1');assert.ok(payload.app_config.app_overrides.initial_bot_message.includes('AI assistant'));});
function fixture(fetcher,env={}){let call={id:'c1',leadId:'l1',source:'CONTACT',phone:'+917814351011',status:'QUEUED',consentAt:new Date(),createdAt:new Date(),requestedAt:null,lead:{name:'Test',businessName:null,serviceInterest:'AI',message:'Help'}};let sends=0;const callback={findUnique:async()=>call,count:async()=>0,update:async({data})=>Object.assign(call,data),updateMany:async({where,data})=>{const matches=where.status===undefined||typeof where.status==='string'&&call.status===where.status||where.status?.in?.includes(call.status);if(matches){Object.assign(call,data);return {count:1};}return {count:0};}};const tx={aiCallback:callback,$executeRaw:async()=>0};const prisma={...tx,$transaction:async f=>f(tx)};const core=load('src/lib/ai-callbacks.ts',{'@/lib/prisma':{prisma},'@/lib/ai-callback-policy':policy},{process:{env:{SARVAM_API_KEY:'test-key',SARVAM_CALLBACKS_ENABLED:'true',...env}},fetch:async(...args)=>{sends++;return fetcher(...args);}});return {core,prisma,call,get sends(){return sends;}};}
test('disabled and nonconsenting records cannot dial',async()=>{const f=fixture(()=>{throw Error('must not call')},{SARVAM_CALLBACKS_ENABLED:'false'});assert.equal(f.core.callbackRecord('CONTACT','7814351011',true).status,'BLOCKED');assert.equal(f.core.callbackRecord('CONTACT','7814351011',false).status,'SKIPPED');await f.core.dispatchCallback('l1');assert.equal(f.sends,0);});
test('accepted call is reserved once and never automatically repeated',async()=>{const f=fixture(async()=>Response.json({attempt_id:'attempt-1'}));await f.core.dispatchCallback('l1');await f.core.dispatchCallback('l1');assert.equal(f.sends,1);assert.equal(f.call.status,'ACCEPTED');assert.equal(f.call.attemptId,'attempt-1');});
test('timeout records uncertainty without retry',async()=>{const f=fixture(async()=>{throw Error('timeout');});await f.core.dispatchCallback('l1');await f.core.dispatchCallback('l1');assert.equal(f.call.status,'UNKNOWN');assert.equal(f.sends,1);});
test('provider validation rejection is distinct from unknown failure',async()=>{const f=fixture(async()=>new Response('',{status:422}));await f.core.dispatchCallback('l1');assert.equal(f.call.status,'REJECTED');});
test('stale queued callback is expired without a call',async()=>{const f=fixture(async()=>Response.json({}));f.call.createdAt=new Date(Date.now()-7200000);await f.core.dispatchCallback('l1');assert.equal(f.call.status,'EXPIRED');assert.equal(f.sends,0);});
test('same phone cooldown prevents another call',async()=>{const f=fixture(async()=>Response.json({}));f.prisma.aiCallback.count=async()=>1;await f.core.dispatchCallback('l1');assert.equal(f.call.status,'SKIPPED');assert.equal(f.sends,0);});
test('webhook verifies token, correlates attempt and is idempotent',async()=>{const f=fixture(async()=>Response.json({attempt_id:'attempt-1'}));await f.core.dispatchCallback('l1');f.call.tokenHash=policy.hashCallbackToken('hook-token');const route=load('src/app/api/callbacks/webhook/route.ts',{'@/lib/prisma':{prisma:f.prisma},'@/lib/ai-callback-policy':policy});const payload={attempt_id:'attempt-1',status:'connected',duration:10,final_agent_variables:{call_summary:'Interested in a demo',call_disposition:'QUALIFIED'},interaction_transcript:[{role:'agent',en_text:'Hello'}],webhook_config:{metadata:{lead_id:'l1',callback_id:'c1'}}};const req=(token,body=payload)=>new Request('https://gravityforai.com/api/callbacks/webhook?id=c1&token='+token,{method:'POST',body:JSON.stringify(body)});assert.equal((await route.POST(req('wrong'))).status,401);assert.equal((await route.POST(req('hook-token',{...payload,attempt_id:'other'}))).status,409);assert.equal((await route.POST(req('hook-token'))).status,200);assert.equal(f.call.status,'CONNECTED');assert.equal(f.call.summary,'Interested in a demo');assert.equal((await route.POST(req('hook-token',{...payload,status:'failed'}))).status,200);assert.equal(f.call.status,'CONNECTED');});
