const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path'),ts=require('typescript');
function load(file,mocks={},globals={}){const absolute=path.resolve(__dirname,'..',file);const module={exports:{}};const source=ts.transpileModule(fs.readFileSync(absolute,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;vm.runInNewContext(source,{module,exports:module.exports,require:id=>id in mocks?mocks[id]:require(id),process,Buffer,URL,Request,Response,Date,AbortSignal,console,...globals});return module.exports;}
const turns=[{role:'agent',en_text:'What do you need?'},{role:'user',en_text:'I want a new website for my bakery. Please email me the recap.'}];
const proposal={intent:'WEBSITE',needs:[{text:'A new website for your bakery.',evidence:'I want a new website for my bakery.',turn:1}],nextSteps:[],needsReview:false,doNotContact:false};
function analysisFixture(outputs){let requests=0;const api=load('src/lib/callback-recap-analysis.ts',{}, {process:{env:{SARVAM_API_KEY:'test'}},fetch:async()=>{const output=outputs[requests++];return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(output)}}]});}});return {api,get requests(){return requests;}};}
test('analysis checks user evidence and independent verifier before allowing recap',async()=>{const f=analysisFixture([proposal,{supported:true,safeToEmail:true,contactAllowed:true}]);const a=await f.api.analyseConversation(turns);assert.equal(a.needsReview,false);assert.equal(f.requests,2);assert.ok(f.api.recapCopy('Test',a).body.includes('bakery'));});
test('invented quotes and agent-only evidence cannot pass',async()=>{const f=analysisFixture([{...proposal,needs:[{text:'Budget agreed',evidence:'10000 dollars',turn:1}]}]);await assert.rejects(()=>f.api.analyseConversation(turns));assert.equal(f.requests,1);assert.equal(f.api.validateEvidence({...proposal,needs:[{text:'x',evidence:'What do you need?',turn:0}]},turns),false);});
test('verifier disagreement holds recap for review',async()=>{const f=analysisFixture([proposal,{supported:false,safeToEmail:true,contactAllowed:true}]);assert.equal((await f.api.analyseConversation(turns)).needsReview,true);});
test('caller opt out suppresses recap without verification or fabricated summary',async()=>{const f=analysisFixture([{...proposal,doNotContact:true}]);assert.equal((await f.api.analyseConversation(turns)).doNotContact,true);assert.equal(f.requests,1);});
test('missing transcript fails closed before model request',async()=>{const f=analysisFixture([]);await assert.rejects(()=>f.api.analyseConversation([]));assert.equal(f.requests,0);});
function engineFixture({analysis=proposal,sendError=false}={}){
 const call={id:'test-call',status:'CONNECTED',analysisStatus:'PENDING',recapStatus:'PENDING',transcriptTurns:turns,lead:{name:'Caller',email:'original@example.com'}};let sends=0,analyses=0,recipient;
 const match=where=>Object.entries(where).every(([k,v])=>call[k]===v);
 const db={findUnique:async()=>call,updateMany:async({where,data})=>{if(!match(where))return {count:0};Object.assign(call,data);return {count:1};},update:async({data})=>Object.assign(call,data)};
 const engine=load('src/lib/callback-recap.ts',{'@/lib/prisma':{prisma:{aiCallback:db}},'@/lib/callback-recap-analysis':{analyseConversation:async()=>{analyses++;return analysis;},recapCopy:()=>({subject:'Recap',body:'A safe recap'})},nodemailer:{createTransport:()=>({sendMail:async msg=>{sends++;recipient=msg.to;if(sendError)throw Error('timeout');return {accepted:[msg.to]};},close:()=>{}})}},{process:{env:{SMTP_HOST:'test',SMTP_USER:'test',SMTP_PASS:'test'}}});
 return {engine,call,get sends(){return sends;},get analyses(){return analyses;},get recipient(){return recipient;}};
}
test('duplicate processing reserves once and emails only original form address',async()=>{const f=engineFixture();await Promise.all([f.engine.safelyProcessCallRecap('test-call'),f.engine.safelyProcessCallRecap('test-call')]);assert.equal(f.analyses,1);assert.equal(f.sends,1);assert.equal(f.recipient,'original@example.com');assert.equal(f.call.recapStatus,'SENT');});
test('missed call and historical call never produce a recap',async()=>{for(const change of [{status:'NO_ANSWER'},{analysisStatus:'NOT_REQUESTED'}]){const f=engineFixture();Object.assign(f.call,change);await f.engine.safelyProcessCallRecap('test-call');assert.equal(f.sends,0);assert.equal(f.analyses,0);}});
test('opt out and uncertain summary prevent all email sends',async()=>{for(const change of [{doNotContact:true},{needsReview:true}]){const f=engineFixture({analysis:{...proposal,...change}});await f.engine.safelyProcessCallRecap('test-call');assert.equal(f.sends,0);assert.ok(['SUPPRESSED','REVIEW'].includes(f.call.recapStatus));}});
test('SMTP uncertainty is retained and never automatically resent',async()=>{const f=engineFixture({sendError:true});await f.engine.safelyProcessCallRecap('test-call');await f.engine.safelyProcessCallRecap('test-call');assert.equal(f.sends,1);assert.equal(f.call.recapStatus,'UNKNOWN');});
